### ISSUE TITLE
Incorrect interpretation of nullable data types

### ISSUE THREAD

**Issue by sergiykhan** [plotly/plotly.py#3495]
## Description
Using Pandas' nullable data types (`Int64` and `Float64`) result in an incorrect plot.

## Code
```
import pandas as pd
import plotly.express as px
df = pd.DataFrame(
    data=[1,2,3,4,5],
    columns=['a'],
    index=pd.date_range('2021-01-01', '2021-01-05'),
    dtype='Int64',
)

px.bar(df)
```

## Result
![wrong](https://user-images.githubusercontent.com/25179211/144480712-73fe2cb8-b4da-4527-baba-f44e7911cec9.png)

## Expected
![correct](https://user-images.githubusercontent.com/25179211/144480732-2a3b9620-8190-4d3a-ab6a-801c3070f434.png)

**Comment by avm19** [comment]
Cannot reproduce in plotly `'5.16.1'`, must've been fixed in or before this version.

**Comment by sergiykhan** [comment]
I have plotly 5.18.0 installed right now, and the problem is still there.

**Comment by avm19** [comment]
> I have plotly 5.18.0 installed right now, and the problem is still there.

I tried in plotly version `5.18.0`, but to no avail. Maybe it depends on other packages in a tricky way.

```python
import pandas as pd
import plotly.express as px
import plotly
df = pd.DataFrame(
    data=[1,2,3,4,5],
    columns=['a'],
    index=pd.date_range('2021-01-01', '2021-01-05'),
    dtype='Int64'
)

px.bar(df, height=300, title=plotly.__version__ + '; ' + pd.__version__)
```
![newplot](https://github.com/plotly/plotly.py/assets/52547519/3c3ded81-77d5-4178-a85a-a1244044d67c)

**Comment by sergiykhan** [comment]
Ah, I am still running Pandas 1.5.3 (due to bugs in 2.x related to timestamp resolution). So, I suppose some issues related to nullable types got fixed in Pandas 2.x.

![1](https://github.com/plotly/plotly.py/assets/25179211/7a0ed7f4-d086-4622-909a-1b2c0e0ebf45)
![2](https://github.com/plotly/plotly.py/assets/25179211/e8237210-fa5a-4814-94b7-877479f13946)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
