### ISSUE TITLE
iplot doesn't display the graph at first in a new browser

### ISSUE THREAD

**Issue by fouhetK** [plotly/plotly.py#506]
hi,
I use Plotly with Jupyter Notebook and it seems that the function to call ipilot in offline mode doesn't always show the graph.

for example:

```
import plotly
import plotly.graph_objs as go
plotly.offline.init_notebook_mode()

trace = go.Bar(x=[2, 4, 6], y= [10, 12, 15])
data = [trace]
layout = go.Layout(title='A Simple Plot', width=800, height=640)
fig = go.Figure(data=data, layout=layout)

plotly.offline.iplot(fig)
```

after accessing the Jupyter Notebook online, when I first go in the notebook with the preview's code, it will not show the graph, I'll need to refresh the tab of the notebook after some time to see it.

there is no error in the console nor anywhere.

plotly version : 1.12.0
python version : 3.4.3
IPython version : 4.2.0

Kevin.

**Comment by yankev** [comment]
How often does this seem to happen?

**Comment by fouhetK** [comment]
on the laptop it seems to appear each time I first start a new browser (if I close it and reopen another one the problem didn't appear).

**Comment by jim-bo** [comment]
I can confirm this behavior everytime on Chrome Version 51.0.2704.84 (64-bit) and plotly version 1.12.2

**Comment by yankev** [comment]
Are you also using `Python 3.4`?

**Comment by jim-bo** [comment]
2.7

**Comment by melvynator** [comment]
Same problem on safari

**Comment by HatuneMiku** [comment]
I have the same problem,

And i use python 3.5; 
chrome 52.0.2743.116 m (64-bit); 
windows 10 1607.
conda                     4.1.11                   py35_0
python                    3.5.2                         0
plotly                    1.12.6                    <pip>
jupyter                   1.0.0                    py35_3
jupyter_client            4.3.0                    py35_0
jupyter_console           5.0.0                    py35_0
jupyter_core              4.1.1                    py35_0
krisk                     0.1.10                    <pip>

but is not just happend in plotly offline, it happens in krisk(a package).
if i open a file that use krisk(on jupyter-notebook), that file will not show the graph, but it show a blank area. and then i open the plotly offline file (on jupyter-notebook) the plotlyoffline-graph will show. and it always be that before i restart my laptop.
so, restart my laptop.
and then i open plotlyoffline-file first, that file will not show the graph(create a new file use plotlyoffline will not show the graph in jupyter same), but krisk_file can show! just like the first_open_file will not show the graph.
so, i think something not work besides this two packages.
I am not good at English, i hope i made it clear.
it also happens when i use edge.

**Comment by empet** [comment]
The same point with python 2.7, plotly 1.12.6.

**Comment by HatuneMiku** [comment]
I change plotly version to 1.9.5 and the fig show again.
I find "init_notebook_mode()" has no parameter at version 1.9.5. But has a default parameter at version 1.12.6.

**Comment by mahadi** [comment]
Same for me with Firefox 48 and plotly 1.12.9

**Comment by jaypeedevlin** [comment]
I got this on plotly-2.0.7, reverting back to 1.9.5 got it to work immediately, but is obviously a sub par solution.  Anyone?

**Comment by stuckeyr** [comment]
Same issue. Firefox 52, Python 3.6.0 (Anaconda 4.3.0 64-bit), Jupyter 4.3.0, jupyter-notebook 5.0.0, plotly-2.0.9. There are no errors/warnings in the log output.
Reverting back to plotly-1.9.5 fixes the issue.

**Comment by armaro** [comment]
I'm facing to the same problem. On both **Firefox 57.0.3 (64-bit)** and **Chromium 63.0.3239.108 (Developer Build) (64-bit)**. Python **3.6.4** and Jupyter Notebook  **5.0.0**.
As @stuckeyr has mentioned, there are neither warnings nor errors. All I get is a white blank space in the output. Seems like the graphs are there but just hidden.
It's considerable that I've just installed **_plotly_** using **pip** command in _Arch Linux_. It's the latest version though.

**Comment by zhivko** [comment]
Same situation as armaro's.

**Comment by farcas** [comment]
Add before plot:
%matplotlib inline

**Comment by Statham-stone** [comment]
save the notebook and refresh the brower

it works for me

**Comment by pierrelzw** [comment]
@Statham-stone 's solution works for me. Thanks!

**Comment by jonmmease** [comment]
Closing as I'm unable to reproduce this issue. Feel free to open a new issue against version 3 if this is still a problem for anyone.

**Comment by sudheerExperiments** [comment]
I have the same problem. I am using plotly version 3.6.1, jupyter lab version 0.32.1, jupyter version 1.0.0, and firefox version 65.0.1.

I tried all the solutions mentioned in this page, but nothing works. When I used **plot** it opens the graph in a new window, but when I used **iplot** just blank space shows up.

P.S. The site is shown as trusted.

My code:

```
trace = go.Scatter(x=x, y= input_data)
data = [trace]
layout = go.Layout(title='A Simple Plot', width=800, height=640)
fig = go.Figure(data=data, layout=layout)

%matplotlib inline
iplot(fig)
```

**Comment by mohitmk98** [comment]
I too had problem in edge browser but works fine in chrome

**Comment by sudheerExperiments** [comment]
> I have the same problem. I am using plotly version 3.6.1, jupyter lab version 0.32.1, jupyter version 1.0.0, and firefox version 65.0.1.
> 
> I tried all the solutions mentioned in this page, but nothing works. When I used **plot** it opens the graph in a new window, but when I used **iplot** just blank space shows up.
> 
> P.S. The site is shown as trusted.
> 
> My code:
> 
> ```
> trace = go.Scatter(x=x, y= input_data)
> data = [trace]
> layout = go.Layout(title='A Simple Plot', width=800, height=640)
> fig = go.Figure(data=data, layout=layout)
> 
> %matplotlib inline
> iplot(fig)
> ```

One way to fix the problem is to install **plotly jupyter lab** extension. The instructions are found on **'plotly.py'** github page.

https://github.com/plotly/plotly.py

**Comment by mcbridecaleb** [comment]
My problem was fixed when I changed my browser from internet explorer (11.0.125) to Chrome.

**Comment by RadCopperman** [comment]
!pip install chart_studio
# Set up the plot layout
layout = go.Layout(height=800, width=800, titlefont=dict(size=20),
                   font=dict(size=16),
                   title='Energy Plot', xaxis=dict(title='Date'),
                   yaxis=dict(title='(kWh)'))

# Create figure and display
fig = go.Figure(data=[energy_data], layout=layout)
iplot(fig)

Google Colab doesn't show anything, just big blank...

**Comment by 411A** [comment]
still having this issue, tried version `1.9.5` but nothing appears.

**Comment by Nishant2116** [comment]
> Add before plot: %matplotlib inline
thanks!!
