### ISSUE TITLE
'secret' plots sometimes show up as 'private' on cloud

### ISSUE THREAD

**Issue by Kully** [plotly/plotly.py#719]
```
for _ in range(50):
    fig = dict(data=[{}], layout={})
    plot_url = py.plot(fig, filename='test_folder/title', fileopt='new', auto_open=False, sharing='secret')
```

^^^Running this code above makes a folder and puts secret graphs into that folder. Out of 50 plots I made, 4 of them were set to private in the cloud.

**Comment by cldougl** [comment]
fixed in https://github.com/plotly/plotly.py/pull/726

**Comment by jordanmuraskin** [comment]
Even in the updated version of plot.ly this error is still occurring for a professional plan user.

**Comment by cldougl** [comment]
https://github.com/plotly/plotly.py/blob/3efe8338df9250cfb5bd7461ed5c9efeac31bb16/plotly/plotly/plotly.py#L1318 is failing silently
